/* Generated by Cython 0.23.4 */

#ifndef __PYX_HAVE___pyemerald
#define __PYX_HAVE___pyemerald


#ifndef __PYX_HAVE_API___pyemerald

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(void) pyemerald_init(void);
__PYX_EXTERN_C DL_IMPORT(gboolean) pyemerald_draw_frame(decor_t *, cairo_t *);

#endif /* !__PYX_HAVE_API___pyemerald */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC init_pyemerald(void);
#else
PyMODINIT_FUNC PyInit__pyemerald(void);
#endif

#endif /* !__PYX_HAVE___pyemerald */
